In [316]:
import random
import numpy as np
import scipy as sc
def graphmaker(v, p):
    for i in range(0,v+1):
        i += 1
        print(i)


In [164]:

#This function generates a list of tuples based on number of vertices and probabilty of forming an edge, does not allow self connection.

def graph(v, p):
    C = []
    for i in range(1,v+1):
        for x in range(1,v+1):
            if x == i:
                continue
            if random.random() <= p:
                C.append([x,i])
            else:
                continue
    return(C)
        

In [168]:
#This converts a list of tuple and size to a matrix
def convert(list,size):
    A = np.zeros((size,size)).astype(int)
    for x in list:
        A[x[0]-1,x[1]-1] =1
    print(A)

In [217]:
#This function generates a matrix representing a graph, based on number of vertices and proability of forming edge, no self-connection.
def matrix(v,p):
    B = []
    A = np.zeros((v,v)).astype(int)
    for i in range(1,v+1):
        for x in range(1,v+1):
            if x == i:
                continue
            if random.random() <= p:
                B.append([x,i])
            else:
                continue
    for t in B:
        A[t[0]-1,t[1]-1] =1
    return(A)
    
    

In [218]:
matrix(4,0.1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [211]:
A = np.zeros((3,3))
B = [[1,1],[2,2],[3,3]]

for x in B:
    A[x[0]-1,x[1]-1]=1
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [324]:
#This converts matrces to a list of tuples
def matrixTotuple(G):
    D=[]
    size = G.shape[0]
    for x in range(0,size):
        for i in range(0,size):
            if G[x,i] == 1:
                D.append([x,i])
            else:
                continue
    return D



In [187]:
A = np.identity(4)
m2t(A)

[[0, 0], [1, 1], [2, 2], [3, 3]]

In [307]:
#This function will take in a graph (as a matrix) and return the number of edges, edge density, and the in/out/total degree of each node
def analyzer(A):
    size = A.shape[0]
    edgeCount = 0
    degout =[]
    degin = []
    for x in range(0,size):
        xout = 0
        for i in range(0,size):
            if A[x,i] == 1:
                edgeCount += 1
                xout +=1
            else:
                continue
        degout.append(xout)
    for i in range(0,size):
        xin = 0
        for x in range(0,size):
            if A[x,i] == 1:
                xin +=1
            else:
                continue
        degin.append(xin)
    print("There are " + str(edgeCount) + " edge(s) in this graph.")
    edgeDensity = edgeCount/(size)/(size-1)
    print("This graph has an edge density of " +str(edgeDensity) + ".")
    print(degin)
    print(degout)
    for t in range(1,size+1):
        print("Node " +str(t) + " has an out-degree of " +str(degout[t-1]) + " and an in degree of " +str(degin[t-1]) + " for a total degree of "+ str(degout[t-1]+degin[t-1]))
    
    


    


In [322]:
A = matrix(4,.5)
print(A)

[[0 1 0 1]
 [1 0 0 1]
 [1 1 0 1]
 [1 1 1 0]]


In [323]:
analyzer(A)

There are 10 edge(s) in this graph.
This graph has an edge density of 0.8333333333333334.
[3, 3, 1, 3]
[2, 2, 3, 3]
Node 1 has an out-degree of 2 and an in degree of 3 for a total degree of 5
Node 2 has an out-degree of 2 and an in degree of 3 for a total degree of 5
Node 3 has an out-degree of 3 and an in degree of 1 for a total degree of 4
Node 4 has an out-degree of 3 and an in degree of 3 for a total degree of 6


In [317]:
x =2 
print("I have " + str(x) + " dogs")

I have 2 dogs
